name: Integração Continua

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Iniciar Banco
      run: docker compose up -d postgres

   # código omitido

    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.59
        args: integracao-continua-projeto/controllers/ database/ models/ routes/
        
    - name: Test
      run: go test -v main_test.go
